### PR TITLE
fixed where winchester looks for its config files to /etc/monasca

### PR DESCRIPTION
**Pull request by SamKirsch10**

### CODE REVIEW

**Comment by tkuhlman** [comment]
The dirs should probably be in vars/main.yml or defaults/main.yml

**Comment by SamKirsch10** [comment]
This isn't the ansible, but they can be added to the ansible role as a template for configurability.

**Comment by tkuhlman** [comment]
Whoops, I shouldn't review and talk at the same time, ignore it.

**Comment by oneilcin** [comment]
looks good to me

**Pull request merged**
